### ISSUE TITLE
[FEATURE] Searchbar

### ISSUE THREAD

**Issue by Zakrok09** [Zakrok09/RoTUer#29]
## Implementation

- [x]  Make "keywords" key for each link
- [x]  Just make a simple algorithm (like the tag filter one) that filters out links whose "keywords"-array doesn't include any items from the "search" array (that contains all words in the search box)
- [x] Make a good design for the searchbox
- [x] Add all keywords to each link

[Suggested ](https://github.com/Zakrok09/RoTUer/discussions/27#discussioncomment-3521501) by [@AntoniosBarotsis](https://github.com/AntoniosBarotsis)

**Comment by paulmis** [comment]
> Just make a simple algorithm (like the tag filter one) that filters out links whose "keywords"-array doesn't include any items from the "search" array (that contains all words in the search box)

Can you explain what are the arrays you mention?

**Comment by Zakrok09** [comment]
> > Just make a simple algorithm (like the tag filter one) that filters out links whose "keywords"-array doesn't include any items from the "search" array (that contains all words in the search box)
> 
> Can you explain what are the arrays you mention?

Yes of course:

The ""keywords" array" refers to a new key in our JSON file. Basically:

```json
...
"keywords": ["shop", "jumbo"...]
```

The search array will be the array of words written in a Search Box (to be put in the next patch).

**Comment by paulmis** [comment]
Ah okay, I was a bit confused with the wording, but I got it now. I could take this issue on.

How is the website hosted ATM? I was thinking of slamming the data into an Openserach domain and running simple DSL queries against it. It would make it very scalable and easy to extend in the future (with new queries and features), but it pretty hefty infrastructure.

**Comment by paulmis** [comment]
To elaborate on how this would work:
- Have a database with documents (=links)
- Describe, categorize, and label each link on the document level
- Create [Opensearch cluster](https://opensearch.org/docs/latest/opensearch/cluster/) and [index/indices](https://opensearch.org/docs/latest/opensearch/index-data/) that index the documents on specific fields
- Update the Opensearch index/indices with document data
- Link the frontend to the cluster through HTTP

The DSL queries let you run the [BM25F](https://en.wikipedia.org/wiki/Okapi_BM25) algorithm which, put in simple terms, lets you perform a weighted search on your document fields. Whenever you get a query like

```
the cat is jumping
```

Opensearch will tokenize it into `cat` and `jumping` and then look for their occurrences in all documents' fields. All documents are then scored based on the number of hits and their weight (repeated hits are scored lower). This lets you give the title and keywords a high weight, while the description would get a lower weight.

**Comment by AntoniosBarotsis** [comment]
This seems pretty overkill for the amount of data currently present, I feel like this could be done completely client-side and achieve adequate (if not better) response times than a solution like this at no extra costs.

I've used [Material MkDocs](https://squidfunk.github.io/mkdocs-material/) in the past and they use https://lunrjs.com/ which (at least in my case) was basically instant. Since the data won't ever be larger than a few kilobytes this should be more than enough (alternatively of course you could DIY it, just sharing the library cause I know it works).

I feel like it would make more sense to try the simpler solution first and then go for the more complex one if needed unless, of course, you want to try that just to see if it works and for the fun of it which I am very often guilty of myself :)

**Comment by Zakrok09** [comment]
We are now working on the Search bar, expect it soon!

**Comment by Zakrok09** [comment]
Feature implemented in #39
