### ISSUE TITLE
[IMPROVEMENT] Programme-specific Pages

### ISSUE THREAD

**Issue by mrn** [Zakrok09/RoTUer#46]
**Problem Description**

There is no place for programme-specific links, but a lot of important links for students are specific to their programme.

**Proposed Sollution**

A page for every programme with links useful only for students in that programme. There should also be a list of all programmes in some menu, to get to each page page.

**Alternatives Considered**

A page for each faculty. But that's not a good idea, because faculties combine multiple programmes, so many links would be useless to other students even in the same faculty. For example, EEMCS combines Computer Science, Mathematics and Electrical Engineering.

**Additional Context**

An example of a website which is very useful to students in the BSc CSE programme but not others is CSHub (https://cshub.nl). Some students made this very useful website which has summaries for various courses.

There are also some interesting study associations which offer jobs, lectures, career events etc., but they are only for some programmes. For example CH (https://ch.tudelft.nl/), a study association for CS and math. But it's not for other students, not even EE students from the same faculty.

**Comment by Zakrok09** [comment]
This is a really good idea and I think it will synergize with #40 (the Dashboard) really well.

The only issue will be acquiring the links themselves for programmes other than CSE. Currently we are working on a Link Maker tool that can be used by anyone to create a JSON object of a link which can be then sent to us. We hope that this will make the process of adding new links a lot faster.

**Comment by AntoniosBarotsis** [comment]
While that is a good idea (and I feel like more people will end up using the website for this rather than the existing resources that are more of a one-time thing until you learn them) it is almost an entirely different website in it itself.

I am probably listing the obvious here but making navigation easy would be crucial for this.

Some ideas & things to consider:

- Do include faculties as a means of grouping the courses making them easier to find, think of it as a system similar to the tags. Looking through EEMCS courses to find CSE instead of *every* course would be faster. It might be worth to consider using the URL (`faculty/course`), especially if it just so happens for 2 courses to share a shortcode (which I don't think is the case but you never know).
- Making these searchable is definitely needed
- Putting each course on its own page will be good for SEO (which was already mentioned, just reinforcing it)
- This will likely be the part of the website for the most community contributions and thus adding new stuff should be as frictionless as possible. I would go as far as to say that using something more flexible like Markdown would perhaps be better than JSON which would require changes in the code every time we need to add some new "component" to the page (probably wouldn't happen often) and would overall, more importantly, be harder to compose.

**Comment by Zakrok09** [comment]
We implemented it currently as a page with a dashboard, from which you can choose which study program you want and it also has tags. The "study program " object can be easily renamed to "faculty" if we desire. 

When you choose a study program, all links related to it appear.

The upload is as friction-less as committing to a JSON file could be (easy for our JSON maintainers). 

Since it only loads links, I don't see the need for making a page for every faculty that you choose. This can still be easily optimized (I believed)

### Here is the problem with markdown

I made an article editor on the webpage that makes articles for our articles page. It complies markdown to HTML. However that is a huge attack vector since you basically can write the HTML of the current page (since there is a loaded preview). Once I realized, I removed it and put it in a different [repository](https://github.com/Zakrok09/rotuer-tools) (partly because I wanted to learn how to do desktop apps with Svelte-Kit) - basically an app that you download (currently available for Windows because I didn't upload the .deb build). It is still built on Svelte-Kit (and Tauri) but it isn't hosted anywhere. 

The thing here is that I can make a tool for people to contribute the JSON directly if they want to, so that we only copy-paste it.

**Comment by Zakrok09** [comment]
You can now see the implementation form #48 here: https://rotuer.praxidike.org/dashboard

**Comment by mrn** [comment]
> I don't see the need for making a page for every faculty

I think Tony meant that navigation will be hell if you only have one menu with 50 programmes. Having a tree-like structure would be easier to navigate.

For example:
```
EEMCS
|
+- BSc CSE
+- BSc EE
+- BSc AE
+- MSc Data Science & Technology
+- MSc Software Technology
+- MSc Artificial Intelligence Technology
+- MSc Electrical Power Engineering
+- MSc Microelectronics
+- MSc Signals & Systems
`- MSc Wireless Communication and Sensing

Aerospace Engineering
|
+- Aerodynamics and Wind Energy
+- Aerospace Structures &amp; Materials
+- Control and Operations
+- Flight Performance and Propulsion
+- Space Flight
+- EWEM: Rotor Design
...
```

These are just 2 faculties, TU Delft has 8

**Comment by Zakrok09** [comment]
I guess we will have to implement them eventually as we grow RoTUer. For now we will stick to the current dashboard.

Thanks for the explanation!

**Comment by mrn** [comment]
For the sake of future-proofing, at least the structure of URL's should be decided at the start. People will start bookmarking URL's and if they save `site/cse` and in the future it changes to `site/eemcs/bsccse` many people will end up with broken links. Redirecting works but it's an ugly fix for something that could be avoided now.

**Comment by Zakrok09** [comment]
That's a really good call. 

Once I start putting them into pages I will make sure to separate them as such

**Comment by Zakrok09** [comment]
We discussed and for now we discarded the idea.
Instead all programmes will be on one page and instead we will make the activeProgram variable changeable from the URL.

**Comment by Zakrok09** [comment]
Forget what I said, I am doing the pages as you said right now

**Comment by Zakrok09** [comment]
# Feature implemented

You can see the modifications at #49
